### ISSUE TITLE
red and green is mixed up

### ISSUE THREAD

**Issue by dodasch** [FabLabRothenburg/wordclock#5]
the red and the green value in the wordclock configuration is mixed up.
So if i want to have red led's i have to set the green value to 255.

**Comment by stesie** [comment]
well, yes and no.

I agree that it is not currently configurable. The problem is that there are different WS2812 led strips.  Those with RGB coding and those with GRB coding. So if you e.g. use the (kind of default)  `DisplayDriverFablabNeaClock` driver, you will find the strip config in `DisplayDriverFablabNeaClock.h` right in line 12.  Just change `NEO_RGB` for `NEO_GRB`. I've got different strips myself, so yes it's annoying...

**Comment by dodasch** [comment]
Okay, i toght that that it has to be a problem with the strips. 
But it works :)
